### ISSUE TITLE
Preparation for use-cases-v0.4

### ISSUE THREAD

**Issue by npyl** [npyl/MyFitnessBuddy#1]
Μικρές αλλαγές για να ξεκινήσουμε να δουλεύουμε προς το Class-diagram-v0.1 και τα use-cases-v0.4

- [x] Προσθήκη της κλάσης ManageDB
- [x] Αφαίρεση της κλάσης FoodOrExercise καθώς η χρήση της αποτελούσε προγραμματιστικό και λογικό σφάλμα.  
- ~Αφαίρεση της κλάσης Day καθώς για την ώρα, κρίναμε ότι δεν ωφελεί να υλοποιηθεί.~
- [x] Προσθήκη των κλάσεων AFoodActivity, AFood, MessageActivity, StatisticsInfo, WorkoutLogEntry, UserInfo, Professional
- [x] Μετονομασία της ExercisePlanner σε Coach

**Comment by Dimitris-Giannakakis** [comment]
Χρειαζόμαστε την Day

**Comment by npyl** [comment]
Σωστά

**Comment by npyl** [comment]
Done... Τώρα πρέπει να δουλέψουμε το κάθε class ξεχωριστά γιατί είναι εντελώς κενά

**Comment by Risos13** [comment]
Θα μοιράσω λίγο τα classes στον καθένα και θα βάλω λιγο παραπάνω σε μενα γτ εχω καθυστερησει κωδικα
